from math import radians, sin, cos, tan
ang = float(input('Digite um ângulo qualquer: '))
print('Segue o valor do seno, cosseno e tangente para o ângulo de {}°. '.format(ang))
rad = radians(ang)
sen = sin(rad)
cos = cos(rad)
tan = tan(rad)
print('=' * 18)
print('O SENO é {:.2f}. \nO COSSENO é {:.2f}. \nA TANGENTE é {:.2f}. '.format(sen, cos, tan))
print('=' * 18)
