alg = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(alg)}')
print('Só tem espaços?', alg.isspace())
print('É um número?', alg.isnumeric())
print('É alfabético?', alg.isalpha())
print('É alfanumérico?', alg.isalnum())
print('Está em maiúsculas?', alg.isupper())
print('Está em minúsculas?', alg.islower())
print('Está capitalizada?', alg.istitle())
