din = float(input('Quanto dinheiro há em sua carteira? R$'))
print('Segue lista de quantos dólares, euros e libras esterlinas poderá comprar:')
print(f'Com R${din:.2f} dá para comprar US${din/5.17:.2f}.')
print(f'Com R${din:.2f} dá para comprar €{din/6.10:.2f}.')
print(f'Com R${din:.2f} dá para comprar GBP{din/6.72:.2f}.')
